# Generated by Django 3.0.7 on 2024-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0011_auto_20220621_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=1000)),
                ('channel', models.CharField(max_length=1000)),
                ('account_id', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'templatestore_template_service_provider',
            },
        ),
    ]
