# Generated by Django 3.0.7 on 2024-09-19 12:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0013_templateserviceprovider_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateserviceprovider',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
