# Generated by Django 3.0.7 on 2024-10-08 09:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0014_auto_20240919_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateversion',
            name='tiny_url',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
